version: '3.8'

services:
  intelligent-intake:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    environment:
      # Core Configuration
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-AIzaSyBzEr9w7CZ4nwp4p-Szqfqc1YgOCqm8nos}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}
      
      # API Authentication
      - DEMANDEI_API_KEY=${DEMANDEI_API_KEY}
      
      # Storage Configuration
      - USE_LOCAL_STORAGE=${USE_LOCAL_STORAGE:-true}
      - LOCAL_STORAGE_PATH=/app/storage
      - LOCAL_DOCUMENTS_PATH=/app/storage/documents
      - LOCAL_SESSIONS_PATH=/app/storage/sessions
      
      # Intake Configuration
      - MAX_QUESTIONS_PER_SELECTION=${MAX_QUESTIONS_PER_SELECTION:-15}
      - ENABLE_CONTEXT_INFERENCE=${ENABLE_CONTEXT_INFERENCE:-true}
      - ENABLE_SMART_FILTERING=${ENABLE_SMART_FILTERING:-true}
      
      # Multi-Agent Configuration
      - ENABLE_MULTI_AGENT=${ENABLE_MULTI_AGENT:-false}
      - CONSENSUS_THRESHOLD=${CONSENSUS_THRESHOLD:-0.7}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - .:/app
      - ./storage:/app/storage
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload