version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      ENVIRONMENT: production
      DEBUG: false
      HOST: 0.0.0.0
      PORT: 8001
      DEMANDEI_API_KEY: ${DEMANDEI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_PRIMARY_MODEL: gemini-1.5-pro
      GEMINI_FALLBACK_MODEL: gemini-1.5-flash
      GEMINI_LAST_RESORT_MODEL: gemini-2.0-flash-exp
      USE_LOCAL_STORAGE: true
      LOCAL_STORAGE_PATH: /app/storage
      ENABLE_REDIS_CACHE: false
      LOG_LEVEL: INFO
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3