
services:
  # Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: ia-compose-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - ia-compose-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  ia-compose-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ia-compose-api
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "${PORT:-8001}:${PORT:-8001}"
    environment:
      # =============================================================================
      # CORE APPLICATION SETTINGS
      # =============================================================================
      ENVIRONMENT: ${ENVIRONMENT:-development}
      DEBUG: ${DEBUG:-false}
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-8001}

      # =============================================================================
      # AUTHENTICATION & SECURITY
      # =============================================================================
      DEMANDEI_API_KEY: ${DEMANDEI_API_KEY}

      # =============================================================================
      # AI CONFIGURATION - GOOGLE GEMINI
      # =============================================================================
      GEMINI_API_KEY: ${GEMINI_API_KEY:-AIzaSyBzEr9w7CZ4nwp4p-Szqfqc1YgOCqm8nos}
      
      # Primary, Fallback, and Last Resort Model Configuration
      GEMINI_PRIMARY_MODEL: ${GEMINI_PRIMARY_MODEL:-gemini-1.5-pro}
      GEMINI_FALLBACK_MODEL: ${GEMINI_FALLBACK_MODEL:-gemini-1.5-flash}
      GEMINI_LAST_RESORT_MODEL: ${GEMINI_LAST_RESORT_MODEL:-gemini-2.0-flash-exp}
      
      # Legacy model field for backward compatibility
      GEMINI_MODEL: ${GEMINI_MODEL:-gemini-1.5-pro}

      # =============================================================================
      # DOCUMENT GENERATION SETTINGS
      # =============================================================================
      DOC_MIN_LINES_PER_STACK: ${DOC_MIN_LINES_PER_STACK:-500}
      DOC_MAX_GENERATION_ATTEMPTS: ${DOC_MAX_GENERATION_ATTEMPTS:-3}
      DOC_GENERATION_TEMPERATURE: ${DOC_GENERATION_TEMPERATURE:-0.8}
      DOC_GENERATION_MAX_TOKENS: ${DOC_GENERATION_MAX_TOKENS:-8000}

      # =============================================================================
      # QUESTION ENGINE SETTINGS
      # =============================================================================
      QUESTION_MAX_PER_SELECTION: ${QUESTION_MAX_PER_SELECTION:-15}
      QUESTION_SIMILARITY_THRESHOLD: ${QUESTION_SIMILARITY_THRESHOLD:-0.7}
      QUESTION_CACHE_TTL_SECONDS: ${QUESTION_CACHE_TTL_SECONDS:-3600}
      QUESTION_GENERATION_TEMPERATURE: ${QUESTION_GENERATION_TEMPERATURE:-0.5}
      QUESTION_GENERATION_MAX_TOKENS: ${QUESTION_GENERATION_MAX_TOKENS:-2048}

      # =============================================================================
      # STORAGE CONFIGURATION
      # =============================================================================
      USE_LOCAL_STORAGE: ${USE_LOCAL_STORAGE:-true}
      LOCAL_STORAGE_PATH: ${LOCAL_STORAGE_PATH:-/app/storage}
      LOCAL_DOCUMENTS_PATH: ${LOCAL_DOCUMENTS_PATH:-/app/storage/documents}
      LOCAL_SESSIONS_PATH: ${LOCAL_SESSIONS_PATH:-/app/storage/sessions}

      # Cloud Storage (Optional for production)
      # GCS_BUCKET_NAME: ${GCS_BUCKET_NAME:-}
      # GCS_CREDENTIALS_PATH: ${GCS_CREDENTIALS_PATH:-}
      # FIRESTORE_PROJECT_ID: ${FIRESTORE_PROJECT_ID:-}

      # =============================================================================
      # SESSION MANAGEMENT
      # =============================================================================
      MAX_SESSION_DURATION: ${MAX_SESSION_DURATION:-3600}
      SESSION_CLEANUP_INTERVAL: ${SESSION_CLEANUP_INTERVAL:-300}

      # =============================================================================
      # API CONFIGURATION
      # =============================================================================
      # CORS is hardcoded in main.py based on ENVIRONMENT variable
      MAX_REQUEST_SIZE: ${MAX_REQUEST_SIZE:-10485760}
      REQUEST_TIMEOUT: ${REQUEST_TIMEOUT:-120}

      # =============================================================================
      # LOGGING CONFIGURATION
      # =============================================================================
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      ENABLE_PII_SAFE_LOGGING: ${ENABLE_PII_SAFE_LOGGING:-true}
      LOG_FILE_PATH: ${LOG_FILE_PATH:-/app/logs/app.log}
      LOG_ROTATION_SIZE: ${LOG_ROTATION_SIZE:-10MB}
      LOG_RETENTION_DAYS: ${LOG_RETENTION_DAYS:-30}

      # =============================================================================
      # PERFORMANCE SETTINGS
      # =============================================================================
      ENABLE_RESPONSE_COMPRESSION: ${ENABLE_RESPONSE_COMPRESSION:-true}
      ENABLE_REQUEST_VALIDATION: ${ENABLE_REQUEST_VALIDATION:-true}
      MAX_CONCURRENT_REQUESTS: ${MAX_CONCURRENT_REQUESTS:-100}

      # =============================================================================
      # REDIS CACHE CONFIGURATION
      # =============================================================================
      ENABLE_REDIS_CACHE: ${ENABLE_REDIS_CACHE:-true}
      
      # Redis connection settings (Docker setup)
      REDIS_HOST: redis  # Always use 'redis' hostname in Docker
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_DB: ${REDIS_DB:-0}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_USERNAME: ${REDIS_USERNAME:-}
      
      # Redis URL alternative (leave empty to use individual settings above)
      REDIS_URL: ${REDIS_URL:-}
      
      # Redis SSL Configuration (usually disabled for local Docker)
      REDIS_SSL: ${REDIS_SSL:-false}
      REDIS_SSL_CERT_REQS: ${REDIS_SSL_CERT_REQS:-required}
      REDIS_SSL_CA_CERTS: ${REDIS_SSL_CA_CERTS:-}
      REDIS_SSL_CERTFILE: ${REDIS_SSL_CERTFILE:-}
      REDIS_SSL_KEYFILE: ${REDIS_SSL_KEYFILE:-}
      
      # Redis Connection Pool Settings
      REDIS_MAX_CONNECTIONS: ${REDIS_MAX_CONNECTIONS:-10}
      REDIS_RETRY_ON_TIMEOUT: ${REDIS_RETRY_ON_TIMEOUT:-true}
      REDIS_HEALTH_CHECK_INTERVAL: ${REDIS_HEALTH_CHECK_INTERVAL:-30}
      REDIS_CONNECTION_TIMEOUT: ${REDIS_CONNECTION_TIMEOUT:-5}
      REDIS_SOCKET_TIMEOUT: ${REDIS_SOCKET_TIMEOUT:-5}
      
      # Cache TTL settings (in seconds)
      REDIS_TTL_QUESTIONS: ${REDIS_TTL_QUESTIONS:-3600}
      REDIS_TTL_DOCUMENTS: ${REDIS_TTL_DOCUMENTS:-86400}
      REDIS_TTL_SESSIONS: ${REDIS_TTL_SESSIONS:-7200}
      
      # Redis Fallback Configuration
      REDIS_ENABLE_FALLBACK: ${REDIS_ENABLE_FALLBACK:-true}
      REDIS_FALLBACK_TIMEOUT: ${REDIS_FALLBACK_TIMEOUT:-2}

      # =============================================================================
      # DEVELOPMENT SETTINGS
      # =============================================================================
      DEV_AUTO_RELOAD: ${DEV_AUTO_RELOAD:-false}  # Disable in Docker for stability
      DEV_DETAILED_ERRORS: ${DEV_DETAILED_ERRORS:-true}
      DEV_LOG_REQUESTS: ${DEV_LOG_REQUESTS:-false}

    volumes:
      # Persistent storage for documents and sessions
      - ./storage:/app/storage
      # Persistent storage for logs
      - ./logs:/app/logs
    
    networks:
      - ia-compose-network
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8001}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


networks:
  ia-compose-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  ia-compose-storage:
    driver: local
  ia-compose-logs:
    driver: local